### ISSUE TITLE
Running from Wine don't work

### ISSUE THREAD

**Issue by zerokol-cmd** [demensdeum/RaidenVideoRipper#74] opened 2023-11-04 10:22 UTC
1. video preview don't work (just black screen)
2. getting video length don't work printing 10 seconds length  
3. Button `Start` outputs `Error while cutting! Result Code: 1`

**Comment by demensdeum** [comment] 2023-11-04 18:06
Interesting...

**Comment by demensdeum** [comment] 2023-11-06 22:27
Probably caused by not so sync duration func of QMediaPlayer, will be fixed in 1.0.1.0

**Comment by demensdeum** [comment] 2023-11-07 19:42
Fixed in 1.0.1.0

**Closed by demensdeum** 2023-11-07 19:42 UTC
